In [1]:
import numpy as np

In [12]:
z=np.zeros((3,2,2,3,2,2,4))

In [14]:
count=0
for k_idx in range(4):
    for q1_idx in range(3):
        for s1_idx in range(2):
            for a1_idx in range(2):
                for q2_idx in range(3):
                    for s2_idx in range(2):
                        for a2_idx in range(2):
                            z[q1_idx,s1_idx,a1_idx,q2_idx,s2_idx,a2_idx,k_idx]=count
                            count+=1

In [15]:
zr=z.reshape((12,12,4))

In [18]:
zr[:,:,0]

array([[  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
         11.],
       [ 12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
         23.],
       [ 24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,  34.,
         35.],
       [ 36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,  45.,  46.,
         47.],
       [ 48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,
         59.],
       [ 60.,  61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.,
         71.],
       [ 72.,  73.,  74.,  75.,  76.,  77.,  78.,  79.,  80.,  81.,  82.,
         83.],
       [ 84.,  85.,  86.,  87.,  88.,  89.,  90.,  91.,  92.,  93.,  94.,
         95.],
       [ 96.,  97.,  98.,  99., 100., 101., 102., 103., 104., 105., 106.,
        107.],
       [108., 109., 110., 111., 112., 113., 114., 115., 116., 117., 118.,
        119.],
       [120., 121., 122., 123., 124., 125., 126., 127., 128., 129., 130.,
        131.],
       [132., 133., 1

In [19]:
zzz=np.zeros((2,3,4))
for k_idx in range(4):
    zzz[:,:,k_idx]=np.array([[0,1,2],[3,4,5]])+6*k_idx


In [21]:
zzz[:,:,0]

array([[0., 1., 2.],
       [3., 4., 5.]])

In [22]:
zzz[:,:,1]

array([[ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [23]:
zzz[:,:,2]

array([[12., 13., 14.],
       [15., 16., 17.]])

In [24]:
zzz[:,:,3]

array([[18., 19., 20.],
       [21., 22., 23.]])

In [27]:
zzz.reshape((6,4))

array([[ 0.,  6., 12., 18.],
       [ 1.,  7., 13., 19.],
       [ 2.,  8., 14., 20.],
       [ 3.,  9., 15., 21.],
       [ 4., 10., 16., 22.],
       [ 5., 11., 17., 23.]])

In [28]:
z1=np.random.rand(2,3,4)
z2=np.random.rand(2,3,4)

In [29]:
z3=np.stack([z1,z2],axis=-1)

In [30]:
z3.shape

(2, 3, 4, 2)

In [33]:
z3[:,:,:,1]==z1

array([[[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]],

       [[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]]])